# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('ruc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('registrado_desde', models.DateField(verbose_name='Registrado desde')),
                ('registrado_hasta', models.DateField(verbose_name='Registrado hasta')),
            ],
        ),
    ]
