# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='registrado_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Registrado hasta'),
        ),
    ]
